name: Validate releases

on: push

jobs:
  test-run:
    name: run-script
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      id: script
      run: |
        python nx-provisioner.py
      shell: sh
    - name: Print errors
      if: steps.script.outputs.error == 'true'
      run: |
        printenv "SCRIPT_STDOUT"
        printenv "SCRIPT_STDERR"
      env:
        SCRIPT_STDOUT: ${{ steps.script.outputs.stdout }}
        SCRIPT_STDERR: ${{ steps.script.outputs.stderr }} 
    - name: Upload drag-n-drop folder
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.head_commit.message }} 
        path: drag-n-drop
